-- create table `room` (
--     id int primary key auto_increment,
--     number varchar(10) not null unique,
--     room_type_id int not null,
--     room_status boolean not null,
--     created_at datetime not null,
--     created_by varchar(255) not null,
--     updated_at datetime not null,
--     updated_by varchar(255) not null
-- )

-- commend is for new feature (can book multiple room)